# -*- coding: utf-8 -*-
"""aula3.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1xllDxhofQ-Sjd3CzC7bgU-fDlPTg5kqb
"""

aluno= input('insira seu nome')
nota1= float(input('primeira nota'))
nota2= float(input('segunda nota'))
media= (nota1+nota2)/2
if media >=7:
    situacao= ('aprovado')
elif media >=5:
    situacao= ('recuperação')
else:
    situacao= ('reprovado')
print(f'o aluno {aluno} foi {situacao} com media {media}')